### PR TITLE
39 duplicate method call refactor

### PR DESCRIPTION
**Pull request by maedae**

### CODE REVIEW

**Comment by sumeetjain** [comment]
I'm a little concerned about overwriting ActiveRecord's `initialize` method–not sure if that will harm the functionality that is has built-in. How about, for example, changing the `get_find_items_for_room` method to:

```
def get_find_items_for_room
    @items_collection ||= Item.where({"room_id" => self.id})
end
```

This is called "memoization", if you want to look it up.

Otherwise, things are looking pretty good. Just remember to make as few changes in this branch as you can.

**Comment by maedae** [comment]
would after_initialize work instead?

# **3.4 after_initialize and after_find**

The after_initialize callback will be called whenever an Active Record object is instantiated, either by directly using new or when a record is loaded from the database. It can be useful to avoid the need to directly override your Active Record initialize method.

The after_find callback will be called whenever Active Record loads a record from the database. after_find is called before after_initialize if both are defined.

The after_initialize and after_find callbacks have no before_\* counterparts, but they can be registered just like the other Active Record callbacks.

class User < ActiveRecord::Base
  after_initialize do |user|
    puts "You have initialized an object!"
  end

  after_find do |user|
    puts "You have found an object!"
  end
end

> > User.new
> > You have initialized an object!
> > => #<User id: nil>
> > 
> > User.first
> > You have found an object!
> > You have initialized an object!
> > => #<User id: 1>

http://guides.rubyonrails.org/v4.1/active_record_callbacks.html

**Comment by sumeetjain** [comment]
Perhaps, but I'm not sure I follow the need for instantiating those variables. I'm sure I just need a quick explanation–I haven't dug into the code deeply enough to see for myself.

**Comment by maedae** [comment]
eventually I just want to try out Short-circuit evaluation as a nil check safeguard and since you have to have your variables declared ahead of time, I thought it might be easier to start with known nil/empty values by default. I can delete the entire method now that I have sorted out what is/isn't an instance variable (we didn't have any the first time around)

**Pull request merged**
